name: Publish todays photo

# Controls when the workflow will run
on:
   schedule:
      - cron: "0 18 * * *"

   # Allows you to run this workflow manually from the Actions tab
   workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
   # This workflow contains a single job called "build"
   build:
      # The type of runner that the job will run on
      runs-on: ubuntu-latest

      # Steps represent a sequence of tasks that will be executed as part of the job
      steps:
         # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
         - uses: actions/checkout@v2

         - name: Setup node
           uses: actions/setup-node@v2-beta
           with:
              node-version: "13"

         - name: Install node dependencies
           run: npm install

         - name: Run script
           env:
              ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
              ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}
              CONSUMER_KEY: ${{ secrets.CONSUMER_KEY }}
              CONSUMER_SECRET: ${{ secrets.CONSUMER_SECRET }}
              NASA_API: ${{ secrets.NASA_API }}
           run: npm run start
